### ISSUE TITLE
Reversable

### ISSUE THREAD

**Issue by asteres** [what3emojis/what3emojis#10]
I don't see a way to lookup an address if I have 3 emoji.

**Comment by harry-wood** [comment]
Yeah I thought it used to show it in the address bar as you panned around. Something like this: https://what3emojis.com/map/#🗂🕔🐴  but maybe that's my imagination.

**Comment by bensheldon** [comment]
@harry-wood your imagination has been fulfilled 🎉 🎉 🎉 : https://what3emojis.com/map/#🗂🕔🐴
