### ISSUE TITLE
tiles don't load in iOS/Safari after search

### ISSUE THREAD

**Issue by burritojustice** [what3emojis/what3emojis#2]
after searching, the emojis load but the tiles don't. however, after rotating from portrait to landscape, they load (and stay loaded after rotation back to portrait). maybe something to do with the oversampling?

**Comment by louh** [comment]
Maybe it has to do with I already am past my limit on Mapbox tiles and they might be throttling me?

**Comment by louh** [comment]
Closing due to age / inactivity
